### ISSUE TITLE
Export raw run times

### ISSUE THREAD

**Issue by PragTob** [PragTob/benchee_csv#1]
Additionally to a CSV with the statistics it'd be nice to also create one that contains the raw run times values per job. Best all in one file if possible, I'm not sure how though.

Not totally sure about the layout of the file. In the first version of the issue I said that the values go into the different columns. But I guess the more CSV way would be to have the values in the rows.

**Comment by elpikel** [comment]
Can I take this one?

**Comment by PragTob** [comment]
Thanks for asking! I refurbished the ticket a bit as I'm not quite sure how the CSV should best look in the end... also not sure if one csv per input or all in one, but all in one would be sort of preferred not sure how to do it though. Do you have an idea? We can sketch table/csv layouts here :D

**Comment by elpikel** [comment]
What do you think about this:

Name, Measure1, Measure2,....,MeasureN
flat_map, 1250.0, 1090.0, ...., 1250.0
map.flatten, 1250.0, 1090.0, ...., 1250.0

?

**Comment by PragTob** [comment]
:wave: 

I'm not sure that that's the most csv way to do things... Somehow I'd expect repeated data to appear in rows. But I dunno. So yeah that is one way, with that we could even get the input names in there:

Name | input name | 1 | 2 | 3 | ... | n

What 'd be a row alternative?

name | name 2
#{measure name_1} | #{measure_name_2_1}

So, yeah I dunno. I think the one you suggested + input name is nice, has the advantage that the data of one scenario is one row so seems good. Thanks :+1:

**Comment by elpikel** [comment]
@PragTob could you close this one?

**Comment by PragTob** [comment]
Ah definitely, my bad :D Thanks for reminding me!
